### ISSUE TITLE
Add example and tests for generating label separately from text input

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-form-builder#477]
We’ve seen a rare use-case where the label might need to be generated separately from the text input: where the text input is in a table cell, and the label is in a different table cell.

I think this can be done like this:

```erb
<tr>
  <th><label class="govuk-label" for="price">Price</label></th>
  <td><%= f.govuk_text_field :price, label: nil %></td>
</tr>
```

However setting `label` to `nil` isn’t documented.

It may also make sense to expose `govuk_label` as a separate helper?

```erb
<tr>
  <th><%= f.govuk_label :price, "Price" %></th>
  <td><%= f.govuk_text_field :price, label: nil %></td>
</tr>
```

However we’d have to be clear that this isn’t the default or easiest way of associating labels with fields.

**Comment by peteryates** [comment]
Yeah I agree about the label helper, it should be quite easy to separate it out as it can just wrap `form.label`.

**Comment by frankieroberto** [comment]
I've split out having a separate label helper into #480 – so that this issue is purely about documenting `label: nil`.
